language: java

before_script:
    - psql -c 'create role learning with password FsoN7e9UTI3EpzrjzXz1oqD3Y;'
    - psql -c 'create database learningsystem;' -U postgres
    - psql -c 'grant all privileges on database learningsystem to learning' -U postgres

service:
    - postgresql
